# Generated by Django 5.2.5 on 2025-08-19 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='stadium.stadium')),
            ],
        ),
    ]
