# Generated by Django 5.2.4 on 2025-07-19 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(help_text='Identificador único del pendiente', primary_key=True, serialize=False)),
                ('userId', models.IntegerField(db_index=True, help_text='ID del usuario propietario del todo', validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(help_text='Título descriptivo del pendiente', max_length=255)),
                ('completed', models.BooleanField(db_index=True, default=False, help_text='Estado del pendiente: True=Resuelto, False=Sin resolver')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('synced_from_api', models.BooleanField(default=False, help_text='Indica si el registro fue sincronizado desde API externa')),
            ],
            options={
                'verbose_name': 'Pendiente',
                'verbose_name_plural': 'Pendientes',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['userId', 'completed'], name='todos_todo_userId_9d1894_idx'), models.Index(fields=['created_at'], name='todos_todo_created_596622_idx')],
            },
        ),
    ]
